stages:
  - build
  - import
  - publish


.artifacts:
  artifacts:
    paths:
    - dist/*.tar.gz
    - dist/*.whl


.always:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour


.devel:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour
  except:
  - tags


.release:
  extends: .artifacts
  artifacts:
    expire_in: 1 hour
  only:
  - tags


.keep:
  extends: .artifacts
  artifacts:
    expire_in: 1000 years
  only:
  - tags


.x86_64-manylinux1: &x86_64-manylinux1
  image: quay.io/pypa/manylinux1_x86_64


.x86_64-manylinux2010: &x86_64-manylinux2010
  image: quay.io/pypa/manylinux2010_x86_64


.x86_64-manylinux2014: &x86_64-manylinux2014
  image: quay.io/pypa/manylinux2014_x86_64


.i686-manylinux1: &i686-manylinux1
  image: quay.io/pypa/manylinux1_i686


.i686-manylinux2010: &i686-manylinux2010
  image: quay.io/pypa/manylinux2010_i686


.i686-manylinux2014: &i686-manylinux2014
  image: quay.io/pypa/manylinux2014_i686


.aarch64-manylinux_2_24: &aarch64-manylinux_2_24
  image: quay.io/pypa/manylinux_2_24_aarch64
  tags:
    - arm



.build: &build
  stage: build
  script:
  - ./build_wheels.sh


.source: &source
  <<: *x86_64-manylinux2014
  stage: build
  script:
  - ./build_source.sh


.publish:
  <<: *x86_64-manylinux2014
  extends: .keep
  stage: publish
  script:
  - ./publish_wheels.sh


devel-x86_64-manylinux1:
  <<: *x86_64-manylinux1
  <<: *build
  extends: .devel


devel-x86_64-manylinux2010:
  <<: *x86_64-manylinux2010
  <<: *build
  extends: .devel


devel-x86_64-manylinux2014:
  <<: *x86_64-manylinux2014
  <<: *build
  extends: .devel


devel-i686-manylinux1:
  <<: *i686-manylinux1
  <<: *build
  extends: .devel


devel-i686-manylinux2010:
  <<: *i686-manylinux2010
  <<: *build
  extends: .devel


devel-i686-manylinux2014:
  <<: *i686-manylinux2014
  <<: *build
  extends: .devel


devel-aarch64-manylinux_2_24:
  <<: *aarch64-manylinux_2_24
  <<: *build
  extends: .devel


devel-source:
  <<: *source
  extends: .devel


release-x86_64-manylinux1:
  <<: *x86_64-manylinux1
  <<: *build
  extends: .release


release-x86_64-manylinux2010:
  <<: *x86_64-manylinux2010
  <<: *build
  extends: .release


release-x86_64-manylinux2014:
  <<: *x86_64-manylinux2014
  <<: *build
  extends: .release


release-i686-manylinux1:
  <<: *i686-manylinux1
  <<: *build
  extends: .release


release-i686-manylinux2010:
  <<: *i686-manylinux2010
  <<: *build
  extends: .release


release-i686-manylinux2014:
  <<: *i686-manylinux2014
  <<: *build
  extends: .release


release-aarch64-manylinux_2_24:
  <<: *aarch64-manylinux_2_24
  <<: *build
  extends: .release


release-source:
  <<: *source
  extends: .release


import-appveyor:
  <<: *x86_64-manylinux2014
  stage: import
  extends: .always
  script:
    - /opt/python/cp39-cp39/bin/python import_appveyor.py
    - ./check_artifacts.sh


publish:
  extends: .publish
  needs: [
    "release-aarch64-manylinux_2_24",
    "release-i686-manylinux1",
    "release-i686-manylinux2010",
    "release-i686-manylinux2014",
    "release-x86_64-manylinux1",
    "release-x86_64-manylinux2010",
    "release-x86_64-manylinux2014",
    "release-source",
    "import-appveyor",
  ]
