branches:
  only:
    - master
    - dev

image:
  - macOS

environment:
  MACOSX_DEPLOYMENT_TARGET: "10.9"
  matrix:
    - platform: x64

for:
  -
    matrix:
      only:
        - image: macOS
    environment:
      PYVERS: "3.6-dev 3.7-dev 3.8-dev 3.9-dev 3.10-dev"
    build_script:
      - ps: ./build_wheels_macos.sh
    artifacts:
      - path: dist/*.whl
