branches:
  only:
    - master
    - dev

image:
  - macOS
  - Visual Studio 2019

environment:
  VCVARSALL: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat'
  MACOSX_DEPLOYMENT_TARGET: "10.9"
  matrix:
    - platform: x86
    - platform: x64

# See appveyor docs for available Python versions:
# https://www.appveyor.com/docs/windows-images-software/#python
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019
          platform: x64
    environment:
      PYVERS: "3.6.8|3.7.9|3.8.10|3.9.7|3.10.0"
      CHOCOARGS: --params "/InstallDir:C:\python"
    build_script:
      - ps: .\build_wheels.ps1
    artifacts:
      - path: dist\*.whl
  -
    matrix:
      only:
        - image: Visual Studio 2019
          platform: x86
    environment:
      PYVERS: "3.6.8|3.7.9|3.8.10|3.9.7|3.10.0"
      CHOCOARGS: --x86 --params "/InstallDir:C:\python"
    build_script:
      - ps: .\build_wheels.ps1
    artifacts:
      - path: dist\*.whl
